package com.example.key.my_carpathians.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.key.my_carpathians.database.Places;

import com.example.key.my_carpathians.database.PlacesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig placesDaoConfig;

    private final PlacesDao placesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        placesDaoConfig = daoConfigMap.get(PlacesDao.class).clone();
        placesDaoConfig.initIdentityScope(type);

        placesDao = new PlacesDao(placesDaoConfig, this);

        registerDao(Places.class, placesDao);
    }
    
    public void clear() {
        placesDaoConfig.clearIdentityScope();
    }

    public PlacesDao getPlacesDao() {
        return placesDao;
    }

}
