package com.example.key.my_carpathians.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PLACES".
*/
public class PlacesDao extends AbstractDao<Places, Long> {

    public static final String TABLENAME = "PLACES";

    /**
     * Properties of entity Places.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PlaceName = new Property(1, String.class, "placeName", false, "PLACE_NAME");
        public final static Property PlaceDescription = new Property(2, String.class, "placeDescription", false, "PLACE_DESCRIPTION");
    }

    private DaoSession daoSession;


    public PlacesDao(DaoConfig config) {
        super(config);
    }
    
    public PlacesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PLACES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PLACE_NAME\" TEXT NOT NULL ," + // 1: placeName
                "\"PLACE_DESCRIPTION\" TEXT NOT NULL );"); // 2: placeDescription
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PLACES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Places entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPlaceName());
        stmt.bindString(3, entity.getPlaceDescription());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Places entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPlaceName());
        stmt.bindString(3, entity.getPlaceDescription());
    }

    @Override
    protected final void attachEntity(Places entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Places readEntity(Cursor cursor, int offset) {
        Places entity = new Places( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // placeName
            cursor.getString(offset + 2) // placeDescription
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Places entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPlaceName(cursor.getString(offset + 1));
        entity.setPlaceDescription(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Places entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Places entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Places entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
